version: '3.8'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql-kaddem
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kaddem
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - kaddem-net

  kaddem-app:
    build:
      context: ./kaddem/kaddem
    container_name: kaddem-app
    ports:
      - "8089:8089"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/kaddem?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
    networks:
      - kaddem-net

volumes:
  db_data:

networks:
  kaddem-net:
